name: DevSecOps Mini Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Run NPM Audit (Dependency Scan)
        # '|| true' mencegah pipeline gagal total jika hanya ada warning dari npm audit.
        # Anda masih bisa melihat hasilnya di log.
        run: npm audit --audit-level=high --json || true

      # Langkah ini menggunakan zricethezav/gitleaks-action@v2 hanya untuk mengunduh dan menyediakan biner gitleaks CLI.
      # Action ini sendiri tidak melakukan pemindaian riwayat penuh secara default,
      # jadi kita akan memanggil CLI secara eksplisit di langkah berikutnya.
      - name: Download Gitleaks CLI
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Diperlukan untuk akses repo jika private

      # Langkah ini menjalankan perintah gitleaks CLI secara langsung.
      # Dengan tidak adanya flag --no-git atau --log-opts, gitleaks v8.x akan memindai
      # seluruh riwayat Git dari awal secara default.
      - name: Execute Gitleaks Full Scan
        run: |
          gitleaks detect --source=. --verbose --redact --exit-code=1
        # 'continue-on-error: false' adalah default, tapi ditekankan di sini
        # untuk memastikan langkah ini menyebabkan pipeline gagal jika leaks ditemukan.
        continue-on-error: false
